id: A9F4484E2
title: Prayer for the Long Life of Namkhai Norbu Rinpoche
type: translation
pechas:
- IA6539A9E
- I9516E550
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:30:53.199372
  last_modified_at: 2023-01-04 11:30:53.199382
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  IA6539A9E/CB4F: 3CF7
  I9516E550/23AB: 3CF7
